kmux:
  sink:
    stream: {{.StreamName}}
  security: spire

knox-gateway:
  server: {{.ServerURL}}
  keepalive:
    time: 5m
    timeout: 10s 
    permitwithoutstream: true

spire:
  spiffeID:
    format: "spiffe://<domainName>/<WSID>/<ClusterID>/<componentName>"
  
  suffixSkipSet:
    - ".sock"
    - ".socket"