name: ci-go

on:
  push:
    branches: [sa-test]
  pull_request:
    branches: [sa-test]

jobs:

  go-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "v1.20"

      - name: Check gofmt
        run: make gofmt

      - name: Run Gosec Security Scanner
        run: make gosec

      - name: Run Revive Action by pulling pre-built imag
        uses: morphy2k/revive-action@v2
        with:
          path: "./..."

  go-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "v1.20"
          
      - name: Configure Git
        run: |
          git config --global user.email "sanjay@accuknox.com"
          git config --global user.name "sanjay-ba"
          git config --global credential.helper '!f() { echo "username=sanjay-ba"; echo "password=${{ secrets.SA-GT }}"; }; f'
          
      - name: Build knoxctl
        run: make

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "v1.20"
          
      - name: Configure Git
        run: |
          git config --global user.email "sanjay@accuknox.com"
          git config --global user.name "sanjay-ba"
          git config --global credential.helper '!f() { echo "username=sanjay-ba"; echo "password=${{ secrets.SA-GT }}"; }; f'

      - name: Run unit tests
        run: make test
